# Generated by Django 4.2.13 on 2024-05-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_alter_teacher_teacher_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='about',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='achievements',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='objectives',
            field=models.TextField(max_length=1500),
        ),
    ]
