# Generated by Django 4.2.13 on 2024-05-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0005_alter_teacher_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_images'),
        ),
    ]
