# Generated by Django 4.2.13 on 2024-05-11 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0007_student_alter_review_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_course', to='mentor.student'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration_hours', models.IntegerField(default=10)),
                ('lectures', models.IntegerField(default=9)),
                ('quizzes', models.IntegerField(default=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course_summary', models.TextField()),
                ('requirements', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='mentor.category')),
                ('favorite', models.ManyToManyField(blank=True, related_name='courses_favorite', to='mentor.student')),
                ('students', models.ManyToManyField(blank=True, related_name='courses_enrolled', to='mentor.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to='mentor.teacher')),
            ],
        ),
    ]
