# Generated by Django 4.2.13 on 2024-05-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0012_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='comment',
            new_name='content',
        ),
    ]
