# Generated by Django 4.2.13 on 2024-05-14 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0015_blog_image_course_image_alter_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_blog_content', to='mentor.blog')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_review', to='mentor.student')),
            ],
        ),
        migrations.CreateModel(
            name='BlogReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_blogreview_content', to='mentor.blogreview')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogreply_review', to='mentor.student')),
            ],
        ),
    ]
