# Generated by Django 4.2.13 on 2024-05-15 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0016_blogreview_blogreviewreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogreviewreply',
            name='replyed_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogreply_replyted_to', to='mentor.student'),
        ),
        migrations.AlterField(
            model_name='blogreview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_review_student', to='mentor.student'),
        ),
        migrations.AlterField(
            model_name='blogreviewreply',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogreply_student', to='mentor.student'),
        ),
    ]
