# Generated by Django 4.2.13 on 2024-05-15 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0018_remove_blogreviewreply_replyed_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogreviewreply',
            old_name='blog',
            new_name='blogreview',
        ),
    ]
