# Generated by Django 4.2.13 on 2024-05-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0019_rename_blog_blogreviewreply_blogreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='BlogReviewReply',
        ),
    ]
