# Generated by Django 4.2.13 on 2024-05-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0021_rename_review_coursereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursereview',
            old_name='rateing',
            new_name='rating',
        ),
    ]
