# Generated by Django 4.2.13 on 2024-05-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0025_product_category_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecurriculum',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
