# Generated by Django 4.2.13 on 2024-05-31 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0027_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_hours',
            field=models.DurationField(),
        ),
    ]
