# Generated by Django 4.2.13 on 2024-06-16 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0028_alter_course_duration_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reviewproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reviewproduct',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ReviewProduct',
        ),
    ]
